#define KEY "eDqcZfqY_i_BHCZVXCwb6aq7GLPKpdV4q1ePja35Mjq"
#define EVENNAME "over30"
#define WIFI_SSID "iPhone"
#define WIFI_PASSWORD "10111005"
#define FIREBASE_HOST "arduinofirebase-6d104.firebaseio.com"
#define FIREBASE_AUTH "z5lPWwjZLZuNNcUEelbJdiNaIvnR2Zfq49BuQBAa"
